"""Shared navigation and location content, verified against mhsrv.com on 2026-09-19."""
from urllib.parse import quote
import site_templates as t
LOCATIONS=[('Alvarado, Texas','5411 South I-35W','Alvarado, TX 76009','8003356054','Mon–Sat 8:30 am–5:30 pm · Sunday closed'),('Palm Desert, California','77840 Varner Rd','Palm Desert, CA 92211','8335191129','Mon–Fri 9 am–7 pm · Sat 9 am–6 pm · Sun 11 am–4 pm'),('Montgomery, Alabama','4504 Troy Hwy','Montgomery, AL 36116','3342880331','Mon–Sat 8:30 am–5:30 pm · Sunday closed')]
SERVICE='https://mhsrv.com/rv-service-rv-parts-and-rv-accessories'

def shopping_menu(prefix=''):
    types=''.join(f'<a href="{prefix}{path}/">{t.TYPE_NAMES[key]}</a>' for key,path in t.TYPE_PATHS.items())
    brands=''.join(f'<a href="{prefix}index.html?q={quote(name)}#inventory">{t.E(name)}</a>' for name in ['American Coach','Brinkley','Coachmen','Dynamax','Entegra Coach','Fleetwood','Forest River','Newmar','Thor Motor Coach','Tiffin','Winnebago'])
    return f'''<details class="shop-menu"><summary>Shop RVs <span aria-hidden="true">⌄</span></summary><div class="shop-menu-panel"><div><h3>Find your starting point</h3><a href="{prefix}index.html#inventory">All RVs</a><a href="{prefix}new-rvs-for-sale/">New RVs</a><a href="{prefix}used-rvs-for-sale/">Pre-owned RVs</a><a href="{prefix}index.html?deal=1#inventory">Deals of the Week</a><a href="{prefix}index.html#budget">Shop by budget</a><a href="{prefix}compare.html">Compare RVs</a></div><div><h3>By RV type</h3>{types}</div><div><h3>By brand</h3>{brands}</div></div></details>'''

def header(prefix='',current='shop',config=None):
    preview=f'<div class="preview-note"><b>Design preview</b> · Inventory snapshot: {t.E(config.get("inventoryDate",""))} · Confirm current price &amp; availability</div>' if config and config['mode']=='preview' else ''
    return f'''<a class="skip-link" href="#main">Skip to content</a>{preview}<header class="site-header"><div class="container header-inner">{t.brand(prefix)}<nav class="desktop-nav" aria-label="Main navigation">{shopping_menu(prefix)}<a href="{prefix}rv-buying-guide.html">Buying guide</a><a href="{prefix}sell-your-rv.html">Sell or trade</a><a class="optional-nav" href="{prefix}reviews.html">Our customers</a></nav><div class="header-actions"><a class="saved-link" href="{prefix}saved.html" aria-label="Saved RVs">{t.icon('heart')}<span class="label">Saved</span><span class="save-count" data-save-count></span></a><a class="header-phone" href="tel:8003356054">Talk to a specialist<b>800-335-6054</b></a><button class="button small" data-lead="Talk to a specialist">Let’s talk {t.icon('arrow')}</button><button class="icon-button mobile-menu" aria-label="Open menu" aria-expanded="false" aria-controls="mobileNav" data-menu>{t.icon('menu')}</button></div></div><nav class="mobile-nav" id="mobileNav" aria-label="Mobile navigation">{shopping_menu(prefix)}<a href="{prefix}rv-buying-guide.html">RV buying guide</a><a href="{prefix}compare.html">Compare RVs</a><a href="{prefix}sell-your-rv.html">Sell, trade or consign</a><a href="{prefix}trade-in.html">RV &amp; auto trade appraisal</a><a href="{prefix}get-prequalified.html">Explore financing</a><a href="{prefix}reviews.html">Customer stories</a><a href="{SERVICE}" target="_blank" rel="noopener">Service &amp; Parts ↗</a><a href="{prefix}about.html">Hours &amp; directions</a><div class="mobile-location-calls"><a href="tel:8003356054">Call Texas</a><a href="tel:8335191129">Call California</a><a href="tel:3342880331">Call Alabama</a><a href="sms:8177907771">Text MHSRV</a></div></nav></header>'''

def locations():
    return '<div class="location-cards">'+''.join(f'<section class="contact-card"><h3>{city}</h3><address>{street}<br>{town}</address><p>{hours}</p><div class="location-actions"><a href="tel:{phone}">{phone[:3]}-{phone[3:6]}-{phone[6:]}</a><a href="https://www.google.com/maps/search/?api=1&amp;query={quote(street+", "+town)}" target="_blank" rel="noopener">Directions ↗</a></div></section>' for city,street,town,phone,hours in LOCATIONS)+'</div>'

def disclaimer():
    return '''<details class="pricing-disclaimer"><summary>Full pricing, financing &amp; promotional terms</summary><div><p>Information is believed reliable but is not guaranteed. Confirm the exact stock number, selling price, availability and installed equipment with the dealership before purchase. Inventory is an imported snapshot. Photos and videos may show representative vehicles, model years or optional equipment. Manufacturer features, dimensions, weights and capacities can change and must be verified on the actual unit.</p><p>MSRP is the manufacturer’s suggested retail price, not necessarily a price previously charged. MSRP for on-order or coming-soon RVs may be estimated from manufacturer information and can change on arrival. Displayed savings percentages are rounded. “Regular advertised price” is supplied by the current inventory feed and does not establish how long that price was offered. Deals include feed-marked specials and units priced at least 42% below listed MSRP; they do not establish a limited-time deadline.</p><p>Sale prices include applicable advertised incentives, offers and rebates unless specified otherwise in writing. Offers cannot be assumed to combine. Prices and promotions are subject to change, including after a promotion ends. Any advertised minimum discount applies only to qualifying vehicles and is not a promise for every RV. Contact sales for the offer terms and eligibility for your stock number.</p><p>Prices and payment estimates exclude tax, title, registration, licensing, insurance and applicable charges unless itemized otherwise. Request a written total. Default payment illustrations use 9.99% APR, 20% down and 240 monthly payments; the assumptions shown beside a calculator or inventory search control its displayed estimates. These examples are not credit offers or advertised available rates. Used RVs and lower financed amounts may qualify for different rates or shorter terms. Actual terms depend on lender approval and the vehicle. Financing inquiries on this site are requests for a conversation, not credit applications or approvals.</p><p><b>Deposits:</b> Under MHSRV’s published purchase terms, deposits are non-refundable unless otherwise specified in writing. A deposit requests that the dealership hold and prepare the selected unit for delivery and orientation. Failure to pay by the agreed delivery date may forfeit the deposit; MHSRV retains discretion to apply part or all of it toward a future purchase. Review and agree to the written deposit and purchase terms with the dealership before paying.</p><p>*#1 refers to American-built motorhomes sold at a single location, per Statistical Surveys, as stated by MHSRV. All site materials are copyright Motor Home Specialist. Reproduction or distribution requires prior written permission. For pricing, promotion, delivery or financing questions, call 800-335-6054.</p></div></details>'''

def footer(prefix='',config=None):
    return f'''<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-brand">{t.brand(prefix)}<p>Big adventures start with the right RV.</p><p>A Blue Compass RV company.</p><a class="footer-text-link" href="sms:8177907771">Text an RV specialist →</a></div><div class="footer-links"><h3>Find your RV</h3><a href="{prefix}new-rvs-for-sale/">New RVs</a><a href="{prefix}used-rvs-for-sale/">Pre-owned RVs</a><a href="{prefix}index.html?deal=1#inventory">Deals of the Week</a><a href="{prefix}saved.html">Your saved RVs</a><a href="{prefix}inventory-pages/1.html">Inventory directory</a><a href="https://mhsrv.com/all-rvs-for-sale" target="_blank" rel="noopener">Full inventory on MHSRV.com ↗</a></div><div class="footer-links"><h3>Make it yours</h3><a href="{prefix}rv-buying-guide.html">Buying guide</a><a href="{prefix}compare.html">Compare RVs</a><a href="{prefix}get-prequalified.html">Financing</a><a href="{prefix}trade-in.html">RV &amp; auto trade appraisal</a><a href="{prefix}sell-your-rv.html">Sell, trade or consign</a></div><div class="footer-links"><h3>We’re here to help</h3><a href="{SERVICE}" target="_blank" rel="noopener">Service &amp; Parts ↗</a><a href="{prefix}about.html">Hours &amp; directions</a><a href="{prefix}reviews.html">Customer stories</a><a href="{prefix}review-pages/1.html">Every customer story</a><a href="mailto:{t.E((config or {}).get('leadEmail','elisha@mhsrv.com'))}">Email MHSRV</a></div></div>{locations()}<div class="footer-base"><span>© 2026 Motor Home Specialist. All rights reserved.</span><span><a href="{prefix}privacy.html">Privacy</a> · <a href="{prefix}your-california-privacy-rights.html">California privacy rights</a> · <a href="{prefix}ccpa-notice.html">CCPA notice</a></span></div>{disclaimer()}</div></footer><nav class="bottom-nav" aria-label="Quick navigation"><a href="{prefix}index.html#inventory">{t.icon('search')}Shop</a><button data-match>{t.icon('spark')}RV Match</button><a href="{prefix}saved.html">{t.icon('heart')}Saved</a><a href="tel:8003356054">{t.icon('phone')}Call</a><a href="sms:8177907771">{t.icon('message')}Text</a></nav><div class="compare-tray" id="compareTray" hidden><div><strong id="compareTrayTitle">Compare your RVs</strong><small>See what makes each one different.</small></div><a href="{prefix}compare.html" class="button yellow">Compare {t.icon('arrow')}</a><button class="icon-button" data-clear-compare aria-label="Clear comparison">{t.icon('close')}</button></div><div class="toast" id="toast" role="status" hidden></div>'''

def about(config):
    from detail_templates import benefits
    return f'''<main id="main" class="container content-page"><div class="page-heading"><p class="eyebrow">Come see the possibilities</p><h1>A better first mile<br>starts with real people.</h1><p>Explore online, talk through your shortlist, and arrive with a plan. Our teams can help you confirm the details before you travel.</p></div><img class="about-showroom" src="assets/showroom.jpg" alt="Motor Home Specialist dealership in Alvarado, Texas" width="1200" height="675"><section class="learn-section"><h2>Your RV. Your questions. Our time.</h2>{benefits()}<div class="resource-actions"><button class="button yellow" data-lead="Plan a dealership visit">Plan my visit {t.icon('arrow')}</button><a class="button outline" href="{SERVICE}" target="_blank" rel="noopener">Service &amp; Parts ↗</a></div></section><section id="locations"><div class="section-heading"><h2>Find your MHSRV team.</h2></div>{locations()}<p class="data-note">Hours are local to each dealership. Confirm holiday hours and delivery arrangements before travel. The Palm Desert location is currently listed by MHSRV as Blue Compass RV Palm Desert.</p></section><section class="learn-section"><div class="section-heading"><h2>Ready for a different chapter?</h2></div><div class="purchase-benefits"><div><b>Tell us about your RV</b><p>Start with its details, condition and your goal: sell, trade or discuss consignment.</p></div><div><b>Get a clear next step</b><p>A specialist reviews your information and arranges the appraisal and any inspection needed for an offer.</p></div></div><a class="button outline" href="sell-your-rv.html">Explore selling options {t.icon('arrow')}</a></section></main>'''
